server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/copilot
    username: root
    password: 123456

jwt:
  header: Authorization
  tokenHead: 'Bearer '
logging:
  level:
    org.springframework.security: DEBUG